/* =====================================================================
   LinkedIn Beautifier — Runtime Controller (content.js)
   ---------------------------------------------------------------------
   Responsibilities
     1. Read persisted state from chrome.storage.local and apply it to
        <body> immediately on load (no layout flash).
     2. Listen for live "LBF_STATE_UPDATE" messages from the popup and
        re-apply instantly.
     3. Continuously tag feed nodes with stable data-attributes via a
        debounced MutationObserver so the CSS design system can target
        them regardless of LinkedIn's autogenerated class names.
   ===================================================================== */

(() => {
  'use strict';

  const STORAGE_KEY = 'lbfState';

  const DEFAULT_STATE = {
    mode: 'classic', // 'zen' | 'executive' | 'classic'
    hideLeft: false,
    hideRight: false,
    hidePromoted: false,
    hideVanity: false,
    killMessaging: false,
  };

  const MODES = ['zen', 'executive', 'classic'];

  /* -------------------------------------------------------------------
     Resilient structural anchors (see initial-request Step 1 mapping)
     ------------------------------------------------------------------- */
  const SEL = {
    leftSidebar: 'aside[aria-label="Sidebar"]',
    rightSidebar: 'aside[aria-label="Aside"]',
    feedRail: 'section[aria-label="Primary content"]',
    feedList: '[data-testid="mainFeed"]',
    // A feed item is a block whose first child is <h2><span>Feed post</span>.
    postHeading: 'h2 > span',
    // Inline / sidebar ad iframe is stably titled + component-keyed.
    adWidget:
      'iframe[title="advertisement"], [componentkey="MainFeedDesktopNav_feed_ad"]',
    // Floating messaging tray (not in feed snippets — use LinkedIn's stable ids).
    messaging:
      '#msg-overlay, .msg-overlay-container, aside[aria-label^="Messaging" i]',
  };

  const POST_HEADING_TEXT = 'feed post';
  const PROMOTED_TEXT = 'promoted';
  // Matches vanity-count summary lines: "1 reaction", "26 comments", "3 reposts".
  const VANITY_SUMMARY_RE =
    /^\s*[\d.,]+\s*(reaction|reactions|comment|comments|repost|reposts|impression|impressions)\b/i;

  let currentState = { ...DEFAULT_STATE };

  /* ===================================================================
     STATE APPLICATION
     =================================================================== */
  function applyState(state) {
    currentState = { ...DEFAULT_STATE, ...state };
    const body = document.body;
    if (!body) return; // Will be retried once <body> exists.

    // Preset mode -> mutually-exclusive body class.
    MODES.forEach((m) => body.classList.remove(`mode-${m}`));
    const mode = MODES.includes(currentState.mode)
      ? currentState.mode
      : DEFAULT_STATE.mode;
    body.classList.add(`mode-${mode}`);

    // Modifiers -> data-attributes.
    body.setAttribute('data-hide-left', String(!!currentState.hideLeft));
    body.setAttribute('data-hide-right', String(!!currentState.hideRight));
    body.setAttribute('data-hide-promoted', String(!!currentState.hidePromoted));
    body.setAttribute('data-hide-vanity', String(!!currentState.hideVanity));
    body.setAttribute('data-kill-messaging', String(!!currentState.killMessaging));

    // Re-tag so newly-relevant nodes (e.g. messaging tray) get their hooks.
    tagFeed();
  }

  /* ===================================================================
     NODE TAGGING  (adds stable data-attributes for the CSS layer)
     =================================================================== */

  // Climb from a marker node to the post-root: the element whose first
  // element child is the "Feed post" <h2>. Falls back to nearest
  // component-keyed ancestor inside the feed list.
  function resolvePostRoot(headingSpan) {
    const h2 = headingSpan.parentElement; // <h2>
    if (!h2) return null;
    const root = h2.parentElement; // block that owns the heading
    return root || null;
  }

  function tagPosts() {
    const list = document.querySelector(SEL.feedList);
    const scope = list || document;
    const headings = scope.querySelectorAll(SEL.postHeading);

    headings.forEach((span) => {
      if ((span.textContent || '').trim().toLowerCase() !== POST_HEADING_TEXT) {
        return;
      }
      const root = resolvePostRoot(span);
      if (!root || root.dataset.lbfPost === 'true') return;

      root.dataset.lbfPost = 'true';

      // Sponsored? Look for a "Promoted" label anywhere inside the post.
      if (isPromoted(root)) {
        root.dataset.lbfSponsored = 'true';
      }

      tagVanityWithin(root);
    });
  }

  function isPromoted(postRoot) {
    // Cheap text scan limited to short label spans keeps this fast.
    const spans = postRoot.querySelectorAll('span, p');
    for (const el of spans) {
      const t = (el.textContent || '').trim().toLowerCase();
      if (t === PROMOTED_TEXT) return true;
      // Guard against long paragraphs that merely contain the word.
      if (t.length <= 12 && t.startsWith(PROMOTED_TEXT)) return true;
    }
    return false;
  }

  // Tag vanity-metric nodes: (a) social-proof summary lines and (b) the
  // numeric counters that sit inside like/comment/repost action buttons.
  function tagVanityWithin(postRoot) {
    // (a) Summary lines such as "1 reaction" / "26 comments".
    postRoot.querySelectorAll('div, span, a').forEach((el) => {
      if (el.dataset.lbfVanity === 'true') return;
      if (el.children.length > 2) return; // leaf-ish only
      const t = (el.textContent || '').trim();
      if (t && t.length <= 24 && VANITY_SUMMARY_RE.test(t)) {
        el.dataset.lbfVanity = 'true';
      }
    });

    // (b) Numeric badge next to reaction / comment / repost buttons.
    postRoot
      .querySelectorAll(
        'button[aria-label="Comment"], button[aria-label="Repost"], button[aria-label^="Reaction"]'
      )
      .forEach((btn) => {
        btn.querySelectorAll('span').forEach((s) => {
          if (s.dataset.lbfVanity === 'true') return;
          if (s.children.length) return; // text leaf only
          const t = (s.textContent || '').trim();
          if (t && /^[\d.,]+[KM]?$/.test(t)) {
            s.dataset.lbfVanity = 'true';
          }
        });
      });
  }

  function tagAdWidgets() {
    document.querySelectorAll(SEL.adWidget).forEach((node) => {
      // Prefer hiding a stable container over the bare iframe so the ad's
      // surrounding chrome disappears too.
      const container =
        node.closest('[data-lbf-post]') ||
        node.closest('[componentkey]') ||
        node.parentElement ||
        node;
      if (container && container.dataset.lbfAdWidget !== 'true') {
        container.dataset.lbfAdWidget = 'true';
      }
    });
  }

  function tagMessaging() {
    document.querySelectorAll(SEL.messaging).forEach((node) => {
      if (node.dataset.lbfMessaging !== 'true') {
        node.dataset.lbfMessaging = 'true';
      }
    });
  }

  function tagFeed() {
    tagPosts();
    tagAdWidgets();
    tagMessaging();
  }

  /* ===================================================================
     DEBOUNCED MUTATION OBSERVER  (infinite scroll enforcement)
     =================================================================== */
  let scheduled = false;
  function scheduleTag() {
    if (scheduled) return;
    scheduled = true;
    // requestIdleCallback keeps tagging off the critical path; falls back
    // to a short timeout where unavailable.
    const run = () => {
      scheduled = false;
      tagFeed();
    };
    if ('requestIdleCallback' in window) {
      requestIdleCallback(run, { timeout: 500 });
    } else {
      setTimeout(run, 250);
    }
  }

  function startObserver() {
    const observer = new MutationObserver((mutations) => {
      for (const m of mutations) {
        if (m.addedNodes && m.addedNodes.length) {
          scheduleTag();
          return;
        }
      }
    });
    observer.observe(document.documentElement, {
      childList: true,
      subtree: true,
    });
  }

  /* ===================================================================
     BOOTSTRAP
     =================================================================== */
  function ensureBody(cb) {
    if (document.body) {
      cb();
      return;
    }
    const bodyWatcher = new MutationObserver(() => {
      if (document.body) {
        bodyWatcher.disconnect();
        cb();
      }
    });
    bodyWatcher.observe(document.documentElement, { childList: true });
  }

  function init() {
    chrome.storage.local.get(STORAGE_KEY, (result) => {
      const saved = (result && result[STORAGE_KEY]) || {};
      ensureBody(() => {
        applyState(saved);
        startObserver();
      });
    });

    // Live updates broadcast from the popup.
    chrome.runtime.onMessage.addListener((message) => {
      if (message && message.type === 'LBF_STATE_UPDATE' && message.state) {
        ensureBody(() => applyState(message.state));
      }
    });

    // Keep in sync if state changes from another tab/instance.
    chrome.storage.onChanged.addListener((changes, area) => {
      if (area === 'local' && changes[STORAGE_KEY]) {
        ensureBody(() => applyState(changes[STORAGE_KEY].newValue || {}));
      }
    });
  }

  init();
})();
